changeLogFile=task.sql

-- Changeset ??? ????????? ??????? Users
-- labels: 0.0.2
-- author: danyil
-- id: create-users-table
--rollback: DROP TABLE IF EXISTS Users;

--liquibase formatted sql

--changeset danyil:create-users-table labels:0.0.2
CREATE TABLE Users (
    ID INT NOT NULL PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL
);
--rollback DROP TABLE Users;


-- Changeset ??? ????????? ??????? ?? Email
-- labels: 0.0.3
-- author: danyil
-- id: create-email-index
--rollback: DROP INDEX idx_users_email ON Users;

--changeset danyil:create-email-index labels:0.0.3
CREATE INDEX idx_users_email ON Users (Email);
--rollback DROP INDEX idx_users_email ON Users;