name: Test

on:
  workflow_dispatch: 
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2

    - name: Patch Liquibase Docker image for 5.x compatibility
      run: |
        docker pull liquibase/liquibase:latest
        printf 'FROM liquibase/liquibase:latest\nUSER root\nRUN echo "changeLogFile=task.sql" >> /liquibase/liquibase.docker.properties\n' | docker build -t liquibase/liquibase:latest -

    - name: Run the bash tests
      run: |
        ./test.sh
